// useNotifications.ts
// ⚠️  This hook was generated by Cursor AI.
// Client reports: "notifications don't always show up, and we've had reports of memory leaks"
// TODO: Review this carefully — AI wrote the happy path, but what did it miss?

import { useState, useEffect, useCallback } from 'react';
import { fetchNotifications, markNotificationRead } from './mockApi';
import type { Notification } from './mockApi';

export function useNotifications(userId: string) {
  const [notifications, setNotifications] = useState<Notification[]>([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    setLoading(true);

    fetchNotifications(userId)
      .then((data) => {
        setNotifications(data);
        setLoading(false);
      });
    // TODO: What happens if this fetch fails?

    // Poll for new notifications every 5 seconds
    // TODO: Is there a problem with how this interval is set up?
    const interval = setInterval(() => {
      fetchNotifications(userId)
        .then((data) => setNotifications(data));
    }, 5000);

    // TODO: What's missing from this effect's return value?
  }, [userId]);

  const markAsRead = useCallback((id: string) => {
    // Optimistic update — immediately show as read
    setNotifications((prev) =>
      prev.map((n) => (n.id === id ? { ...n, read: true } : n))
    );

    // Sync to server — fire and forget
    // TODO: What happens if this fails?
    markNotificationRead(id);
  }, []);

  const unreadCount = notifications.filter((n) => !n.read).length;

  return { notifications, loading, unreadCount, markAsRead };
}
